ag_names:
  - GPTScorer
  - GPT5Scorer
  - DSR1Scorer
  - DSV3Scorer
config_mapping:
  GPTScorer: ./metrics/asr/config/gpt_scorer.yaml
  GPT5Scorer: ./metrics/asr/config/gpt5_scorer.yaml
  DSR1Scorer: ./metrics/asr/config/dsr1_scorer.yaml
  DSV3Scorer: ./metrics/asr/config/dsv3_scorer.yaml
