apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teleai-safety-data-pvc
  namespace: teleai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "100Gi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teleai-safety-benchmark-pvc
  namespace: teleai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "100Gi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teleai-safety-evaluate-pvc
  namespace: teleai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "100Gi"
